DDCE-3390: added origin to login urls and added continue url to signe…
hmrc/maintain-lead-trustee-frontend pull request #269
Opened 2022-11-30 14:25 UTC by fraser-sprott

…d out page login button

2022-12-06 10:44 UTC, ina-tu requested changes

2022-12-06 10:44 UTC, ina-tu commented on run_all_test.sh
> +sbt clean scalastyleAll compile coverage test it:test coverageOff coverageReport dependencyUpdate
this should be "dependencyUpdates"

2022-12-22 00:34 UTC, anu9 commented on run_all_test.sh
> +sbt clean scalastyleAll compile coverage test it:test coverageOff coverageReport dependencyUpdate
Done

2023-02-02 17:24 UTC, zmdnoor approved these changes

2023-02-02 17:40 UTC, zmdnoor approved these changes

2023-02-03 10:51 UTC, merged