DDCE-4194: Update CSP config
hmrc/maintain-lead-trustee-frontend pull request #277
Opened 2023-08-25 09:20 UTC by MRBeresford

2023-08-31 11:43 UTC, matthewwardcap requested changes
Good few minor comments:

1) in run_all_tests.sh change `it:test` to `IntegrationTest/test`

2) In build.sbt line 76. Change `addCommandAlias("scalastyleAll", "all scalastyle test:scalastyle it:scalastyle")` to `addCommandAlias("scalastyleAll", "all scalastyle Test/scalastyle IntegrationTest/scalastyle")`
also change coverage from 70 to 93

3) in plugins.sbt remove line 3, replace lines 1/2 with:
`resolvers += MavenRepository("HMRC-open-artefacts-maven2", "https://open.artefacts.tax.service.gov.uk/maven2")`
`resolvers += Resolver.url("HMRC-open-artefacts-ivy2", url("https://open.artefacts.tax.service.gov.uk/ivy2"))(Resolver.ivyStylePatterns)`

2023-08-31 16:09 UTC, MRBeresford commented on conf/application.conf
> -      enabled = true
I used to leave `enabled=true` in here but is this doing anything locally? its overwritten in all other envs so do we need it here?

2023-09-01 09:18 UTC, MRBeresford commented on conf/application.conf
> -      enabled = true
Set to true in app-config-common

2023-09-01 09:21 UTC, matthewwardcap approved these changes
All good to me

2023-09-01 09:21 UTC, merged